# Generated by Django 3.0.5 on 2020-04-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('symptom', models.CharField(max_length=40)),
                ('selection_count', models.IntegerField()),
            ],
        ),
    ]
