# Generated by Django 3.0.5 on 2020-04-17 17:46

from django.db import migrations

def create_data(apps, schema_editor):
    Diagnosis = apps.get_model('diagnoses', 'Diagnosis')

    Diagnosis(name="Common cold", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Viral throat infection", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Middle ear infection", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Seasonal allergies", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Strep throat", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Mononucleosis infection", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Bronchitis", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Acid reflux disease", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Acute bacterial sinusitis", symptom="Sore throat", selection_count=0).save()
    Diagnosis(name="Sunburn", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Irritant contact dermatitis", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Non-specific dermatitis", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Hives", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Benign skin growth", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Allergic reaction", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Chronic hepatitis", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Shingles (herpes zoster)", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Perianal skin infection", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Seborrheic dermatitis", symptom="Itchy rash", selection_count=0).save()
    Diagnosis(name="Common cold", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Chronic sinusitis", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Non-allergic rhinitis", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Chronic allergies", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Normal congestion", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Mononucleosis infection", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Viral infection of the nose", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Chronic bronchitis", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Hand-foot-and-mouth disease", symptom="Runny nose", selection_count=0).save()
    Diagnosis(name="Bronchiectasis", symptom="Runny nose", selection_count=0).save()

class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
